//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace cf.Module.BusinessObjects.ORMDataModel1
{

    public partial class Dinhluong : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Sanpham fSanpham_ID;
        [Association(@"DinhluongReferencesSanpham")]
        public Sanpham Sanpham_ID
        {
            get { return fSanpham_ID; }
            set { SetPropertyValue<Sanpham>(nameof(Sanpham_ID), ref fSanpham_ID, value); }
        }
        Sanpham fThanhphan_ID;
        [Association(@"DinhluongReferencesSanpham1")]
        public Sanpham Thanhphan_ID
        {
            get { return fThanhphan_ID; }
            set { SetPropertyValue<Sanpham>(nameof(Thanhphan_ID), ref fThanhphan_ID, value); }
        }
        string fSoluong;
        public string Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<string>(nameof(Soluong), ref fSoluong, value); }
        }
    }

}
