//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace cf.Module.BusinessObjects.ORMDataModel1
{

    public partial class Dongnhap : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Sanpham fSanpham_ID;
        [Association(@"DongnhapReferencesSanpham")]
        public Sanpham Sanpham_ID
        {
            get { return fSanpham_ID; }
            set { SetPropertyValue<Sanpham>(nameof(Sanpham_ID), ref fSanpham_ID, value); }
        }
        Phieunhap fNhap_ID;
        [Association(@"DongnhapReferencesPhieunhap")]
        public Phieunhap Nhap_ID
        {
            get { return fNhap_ID; }
            set { SetPropertyValue<Phieunhap>(nameof(Nhap_ID), ref fNhap_ID, value); }
        }
        int fSoluong;
        public int Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<int>(nameof(Soluong), ref fSoluong, value); }
        }
        decimal fDongia;
        public decimal Dongia
        {
            get { return fDongia; }
            set { SetPropertyValue<decimal>(nameof(Dongia), ref fDongia, value); }
        }
    }

}
