//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace cf.Module.BusinessObjects.ORMDataModel1
{

    public partial class HoadonCT : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Hoadon fHoadon_ID;
        [Association(@"HoadonCTReferencesHoadon")]
        public Hoadon Hoadon_ID
        {
            get { return fHoadon_ID; }
            set { SetPropertyValue<Hoadon>(nameof(Hoadon_ID), ref fHoadon_ID, value); }
        }
        Sanpham fSanpham_ID;
        [Association(@"HoadonCTReferencesSanpham")]
        public Sanpham Sanpham_ID
        {
            get { return fSanpham_ID; }
            set { SetPropertyValue<Sanpham>(nameof(Sanpham_ID), ref fSanpham_ID, value); }
        }
        int fSoluong;
        public int Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<int>(nameof(Soluong), ref fSoluong, value); }
        }
        decimal fDongia;
        public decimal Dongia
        {
            get { return fDongia; }
            set { SetPropertyValue<decimal>(nameof(Dongia), ref fDongia, value); }
        }
        [PersistentAlias("ToDecimal([Soluong] * [Dongia])")]
        public string Thanhtien
        {
            get { return (string)(EvaluateAlias(nameof(Thanhtien))); }
        }
        [Association(@"TieuhaoReferencesHoadonCT"), Aggregated]
        public XPCollection<Tieuhao> Tieuhaos { get { return GetCollection<Tieuhao>(nameof(Tieuhaos)); } }
    }

}
