//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace cf.Module.BusinessObjects.ORMDataModel1
{

    public partial class Khachhang : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fHoten;
        public string Hoten
        {
            get { return fHoten; }
            set { SetPropertyValue<string>(nameof(Hoten), ref fHoten, value); }
        }
        string fDienthoai;
        public string Dienthoai
        {
            get { return fDienthoai; }
            set { SetPropertyValue<string>(nameof(Dienthoai), ref fDienthoai, value); }
        }
        [Association(@"HoadonReferencesKhachhang"), Aggregated]
        public XPCollection<Hoadon> Hoadons { get { return GetCollection<Hoadon>(nameof(Hoadons)); } }
    }

}
