//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace cf.Module.BusinessObjects.ORMDataModel1
{

    public partial class Phieuchi : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Nhanvien fNhanvien_ID;
        [Association(@"PhieuchiReferencesNhanvien")]
        public Nhanvien Nhanvien_ID
        {
            get { return fNhanvien_ID; }
            set { SetPropertyValue<Nhanvien>(nameof(Nhanvien_ID), ref fNhanvien_ID, value); }
        }
        Nhacungcap fNCC_ID;
        [Association(@"PhieuchiReferencesNhacungcap")]
        public Nhacungcap NCC_ID
        {
            get { return fNCC_ID; }
            set { SetPropertyValue<Nhacungcap>(nameof(NCC_ID), ref fNCC_ID, value); }
        }
        string fSo;
        public string So
        {
            get { return fSo; }
            set { SetPropertyValue<string>(nameof(So), ref fSo, value); }
        }
        string fNgay;
        public string Ngay
        {
            get { return fNgay; }
            set { SetPropertyValue<string>(nameof(Ngay), ref fNgay, value); }
        }
        string fSotien;
        public string Sotien
        {
            get { return fSotien; }
            set { SetPropertyValue<string>(nameof(Sotien), ref fSotien, value); }
        }
    }

}
